### ISSUE TITLE
Include wait_for_update on the setDefaultConsent Call

### ISSUE THREAD

**Issue by semisight** [Cookie-Script/GTM-tag-template#1]
When reviewing your template we've noticed that the setDefaultConsentState call does not include the [wait_for_update](https://developers.google.com/tag-platform/tag-manager/templates/api#setdefaultconsentstate) option. This is required for any asynchronous consent management script load to delay tag execution.

**Comment by Cookie-Script** [comment]
@semisight The issue is now fixed, please review

**Comment by Cookie-Script** [comment]
@semisight Can you please review and validate the template at Community Template Gallery?

**Comment by Cookie-Script** [comment]
@semisight the issue has been resolved, please re-validate the template. It's been 9 months since the issue was resolved and the template is still not added to the template gallery.

**Comment by semisight** [comment]
Apologies, this pull request just slipped through the cracks. Your template should be available in Gallery momentarily.
